apps/community/urls.py
from django.urls import path
from django.shortcuts import render
from .views import *

# from * import views

app_name = "community"

urlpatterns = [
    path("<int:board_id>/", post_list, name="post_list"),
    path("<int:board_id>/post/<int:post_id>/", post_detail, name="post_detail"),
    path("<int:board_id>/create/", create_post, name="create_post"),
    path("create_board/", create_board, name="create_board"),
    path("", main, name="main"),
    path("<int:board_id>/delete/", delete_board, name="delete_board"),
    path("create_club/", create_club, name="create_club"),
    path("select_club/", select_club, name="select_club"),
    path("post/<int:post_id>/scrap/", scrap_post, name="scrap_post"),
    path("post/<int:post_id>/like/", like_post, name="like_post"),
    path(
        "<int:board_id>/post/<int:post_id>/create_comment/",
        create_comment,
        name="create_comment",
    ),
    path(
        "<int:board_id>/post/<int:post_id>/toggle_pinned/",
        toggle_pinned,
        name="toggle_pinned",
    ),
    path("post/<int:post_id>/delete/", delete_post, name="delete_post"),
    path("comment/<int:comment_id>/delete/", delete_comment, name="delete_comment"),
    path("search", search, name="search"),
    path("load-more-boards/", load_more_boards, name="load_more_boards"),
    path("<int:post_id>/delete_post/", delete_post, name="delete_post"),
]

apps/mypage/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from . import views

app_name = "mypage"

urlpatterns = [
    path("", main, name="main"),
    path("myposts/", myposts, name="myposts"),
    path("mycomments/", mycomments, name="mycomments"),
    path("myscraps/", myscraps, name="myscraps"),
    path('manage-clubs/', views.manage_clubs, name='manage_clubs'),
    path('delete-club/', views.delete_club, name='delete_club'),
    path('switch_club/<int:club_id>/', views.switch_club, name='switch_club'),
    path('webpush/get_status/', views.get_status, name='get_status'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.landing.urls")),  # 랜딩 페이지 ~ 동아리 인증페이지까지
    path("community/", include("apps.community.urls")),  # 메인 페이지 ~ 모든 기능
    path("chat/", include("apps.chat.urls")),  # 채팅방 리스트, 채팅방
    path("mypage/", include("apps.mypage.urls")),  # 마이페이지 내 모든 기능
    path("schedule/", include("apps.schedule.urls")),
    path("", include("django.contrib.auth.urls")),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="registration/password_reset_form.html"
        ),
        name="password_reset_form",
    ),
    path(
        "password_reset_done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="registration/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("webpush/", include("webpush.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/community/models.py
from django.db import models
from django.contrib.auth import get_user_model


# Create your models here.
class Club(models.Model):  # 동아리
    club_name = models.CharField("동아리명", max_length=255, unique=True)
    club_num = models.CharField(
        "동아리 인증 번호", max_length=255, unique=True, null=False
    )

    # 동아리 이름 표시용
    def __str__(self):
        return self.club_name


class Board(models.Model):  # 게시판
    club_id = models.ForeignKey(Club, on_delete=models.CASCADE)
    # 게시판 이름 같아도 이제 club_id field 있으니 구분 가능함, 동아리가 달라도 게시판 이름은 같을 수 있으니 unique 불가
    board_name = models.CharField("게시판 이름", max_length=255, unique=False)

    # 게시판 이름 표시용
    def __str__(self):
        return f"{self.board_name} ({self.club_id} 동아리)"


class Post(models.Model):  # 게시글
    user_id = models.ForeignKey("landing.User", on_delete=models.CASCADE)
    club_id = models.ForeignKey(Club, on_delete=models.CASCADE)
    board_id = models.ForeignKey(Board, on_delete=models.CASCADE)
    title = models.CharField("게시글 제목", max_length=255)
    content = models.TextField("게시글 내용")
    anonymous = models.BooleanField("익명 여부", default=True)
    created_time = models.DateTimeField("작성 시각", auto_now_add=True)
    image = models.ImageField(upload_to="post_images/", null=True, blank=True)
    pinned = models.BooleanField("게시글 고정 여부", default=False)
    liked_by = models.ManyToManyField(
        get_user_model(), related_name="liked_posts", blank=True
    )
    liked_cnt = models.IntegerField(default=0)
    scrap_cnt = models.IntegerField(default=0)
    scraped_by = models.ManyToManyField(
        get_user_model(), through="mypage.Scrap", related_name="scraped_posts"
    )

    def __str__(self):
        return self.title


class Comment(models.Model):  # 댓글
    user_id = models.ForeignKey("landing.User", on_delete=models.CASCADE)
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField("댓글 내용")
    anonymous = models.BooleanField("익명 여부", default=True)
    created_time = models.DateTimeField(auto_now_add=True)
    parent_id = models.ForeignKey(
        "community.Comment", null=True, on_delete=models.CASCADE
    )
    depth = models.IntegerField("댓글 깊이", default=0)
    liked = models.IntegerField("좋아요 개수", default=0)

    # 댓글 내용 표시용
    def __str__(self):
        return self.content

apps/community/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from django.urls import reverse
from .models import Board, Post, Comment, Club
from apps.mypage.models import Scrap
from apps.landing.models import User, Auth_Club
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import CommentForm, PostForm, BoardForm, ClubForm
from django.http import JsonResponse
from webpush import send_group_notification
from webpush import send_user_notification

# Create your views here.


def create_club(request):
    if request.user.is_authenticated:
        if request.method == "GET":
            print(request.POST)
            form = ClubForm()
            return render(request, "community/create_club.html", {"form": form})
        if request.method == "POST":
            form = ClubForm(request.POST)
            if form.is_valid():
                club = form.save()
                request.session["club_id"] = club.pk  # 세션에 동아리 고유번호 저장
                request.session["club_name"] = club.club_name  # 세션에 동아리 이름 저장
                request.user.is_admin = True
                request.user.save()

                # Auth_Club 모델에 유저와 동아리 정보 저장
                Auth_Club.objects.create(user_id=request.user, club_id=club)

                # 기본 게시판 객체 생성
                default_boards = ["공지게시판", "자유게시판", "질문게시판"]
                for board_name in default_boards:
                    Board.objects.create(club_id=club, board_name=board_name)

                return redirect("community:main")
            else:
                return render(request, "community/create_club.html", {"form": form})
    else:
        return redirect("landing:login")


def select_club(request):
    if request.user.is_authenticated:
        # 사용자가 가입한 동아리 리스트 가져오기
        user_clubs = Auth_Club.objects.filter(user_id=request.user)
        club_id = request.session.get("club_id")
        boards = Board.objects.filter(club_id=club_id)
        if request.method == "POST":
            selected_club_id = request.POST.get("club_id")
            club = Club.objects.get(id=selected_club_id)
            if selected_club_id:
                request.session["club_id"] = selected_club_id
                request.session["club_name"] = club.club_name
                return redirect("community:main")

        return render(
            request,
            "community/select_club.html",
            {"user_clubs": user_clubs, "boards": boards},
        )
    else:
        return redirect("landing:login")


def post_list(request, board_id):
    if request.user.is_authenticated:
        club_id = request.session.get("club_id")
        board = get_object_or_404(Board, id=board_id, club_id=club_id)
        posts = Post.objects.filter(board_id=board, club_id=club_id).order_by(
            "-pinned", "-created_time"
        )
        form = PostForm(initial={"anonymous": True})
        boards = Board.objects.filter(club_id=club_id)
        posts_best = Post.objects.filter(club_id=club_id, liked_cnt__gte=5)
        return render(
            request,
            "community/post_list.html",
            {
                "board": board,
                "posts": posts,
                "form": form,
                "boards": boards,
                "posts_best": posts_best,
            },
        )
    else:
        return redirect("landing:login")


def post_detail(request, board_id, post_id):
    if request.user.is_authenticated:
        board = get_object_or_404(Board, id=board_id)
        post = get_object_or_404(Post, id=post_id)
        comments = Comment.objects.filter(post_id=post_id)
        club_id = request.session.get("club_id")
        boards = Board.objects.filter(club_id=club_id)
        posts_best = Post.objects.filter(club_id=club_id, liked_cnt__gte=5)

        is_liked = request.user in post.liked_by.all()

        if request.method == "POST":
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.post_id = post
                comment.user_id = request.user
                comment.save()

                # 알림을 보낼 사용자 목록
                notification_users = set()

                # 게시글 작성자에게 알림
                notification_users.add(post.user_id)

                # 부모 댓글이 있는 경우, 부모 댓글 작성자에게 알림
                if comment.parent_id:
                    notification_users.add(comment.parent_id.user_id)

                    # 부모 댓글에 달린 자식 댓글의 작성자도 알림 대상에 추가
                    child_comments = Comment.objects.filter(parent_id=comment.parent_id)
                    for child_comment in child_comments:
                        notification_users.add(child_comment.user_id)

                # 알림 보내기
                # 알림 url 생성
                comment_url = request.build_absolute_uri(
                    reverse("community:post_detail", args=[board_id, post_id])
                )
                payload = {
                    "head": f'"{post.title}"에 새로운 댓글이 달렸습니다.',
                    "body": f"{comment.content[:10]}",
                    "url": comment_url,  # paload에 url 추가
                }

                # 디버그용
                print(notification_users)

                for user in notification_users:
                    if user != request.user:  # 자신에게는 알림을 보내지 않음
                        print("post detail에서 알림")
                        send_user_notification(user=user, payload=payload, ttl=1000)

                # 그룹 알림 필요할때 사용
                # send_group_notification(
                #     group_name=notification_users, payload=payload, ttl=1000
                # )

                return redirect(
                    "community:post_detail", board_id=board.id, post_id=post.id
                )
        else:
            form = CommentForm()

        return render(
            request,
            "community/post_detail.html",
            {
                "board": board,
                "post": post,
                "comments": comments,
                "form": form,
                "is_liked": is_liked,
                "likes_count": post.liked_by.count(),
                "boards": boards,
                "posts_best": posts_best,
                "scrap_count": post.scraped_by.count(),
            },
        )
    else:
        return redirect("landing:login")


"""
def create_post(request, board_id):
    if request.user.is_authenticated:

        board = get_object_or_404(Board, pk=board_id)
        club_id = request.session.get("club_id")
        club = Club.objects.get(id=club_id)
        if request.method == "POST":
            form = PostForm(request.POST)
            # form = PostForm(request.POST, request.FILES)
            if form.is_valid():
                post = form.save(commit=False)
                post.user_id = request.user
                post.club_id = club
                post.board_id = board
                post.save()

                # if 'image' in request.FILES:
                # pass

                return redirect("community:post_list", board_id=board.id)
        else:
            form = PostForm(initial={"anonymous": True})

        return render(
            request, "community/create_post.html", {"form": form, "board": board}
        )
    else:
        return redirect("landing:login")
"""


def create_post(request, board_id):
    if request.user.is_authenticated:
        board = get_object_or_404(Board, pk=board_id)
        club_id = request.session.get("club_id")
        club = Club.objects.get(id=club_id)
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user_id = request.user
            post.club_id = club
            post.board_id = board
            post.save()

            # 공지게시판에 글 작성시 공지게시판의 동아리원 전부에게 알림 전송
            if board.board_name == "공지게시판":
                # 알림을 보낼 사용자 목록
                notification_users = set()

                # Auth_Club 모델에서 글을 작성하는 공지 게시판 동아리의 소속 동아리원들을 가져옴
                club_members = Auth_Club.objects.filter(club_id=club_id)
                for club_member in club_members:
                    notification_users.add(club_member.user_id)

                # 알림 보내기
                # create_post로 인해 만들어진 post의 절대 url 생성
                post_url = request.build_absolute_uri(
                    reverse("community:post_detail", args=[board.id, post.id])
                )
                payload = {
                    "head": f"{club.club_name} 동아리에 새로운 공지사항이 등록되었습니다.",
                    "body": f"{post.title}",
                    "url": post_url,  # paload에 url 추가

                }

                # 디버그용
                print(notification_users)

                for user in notification_users:
                    if (
                        user != request.user
                    ):  # 자신에게는 알림을 보내지 않음, 알림 버튼 활성화인 유저한테만 보냄

                        send_user_notification(user=user, payload=payload, ttl=1000)

                # 그룹 알림 필요할때 사용
                # send_group_notification(
                #     group_name=notification_users, payload=payload, ttl=1000
                # )

            return JsonResponse(
                {
                    "status": "success",
                    "post_id": post.id,
                    "board_name": board.board_name,
                    "title": post.title,
                    "content": (
                        post.content[:100] + "..."
                        if len(post.content) > 100
                        else post.content
                    ),
                    "created_time": post.created_time.strftime("%Y/%m/%d"),
                    "user_name": post.user_id.name,
                    "user": post.user_id.nickname if not post.anonymous else "익명",
                    "anonymous": post.anonymous,

templates/community/create_board.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/community/create_board.css' %}" />
<div class="c_b_frame">    
    <div class="c_b_title">
        <h1 class="c_b_h1">새 게시판 생성</h1>
    </div>
    <div class="c_b_line">

    </div>
    <div class="c_b_container">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn-primary">게시판 만들기</button>
        </form>
    </div>
</div>
{% endblock %}

templates/community/create_club.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/reset.css' %}">
<link rel="stylesheet" href="{% static 'css/community/create_club.css' %}">
<link rel="stylesheet" href="{% static 'css/users/signup.css' %}">
    <div id="createclub-container">
        <h3>동아리 생성</h3>
        <form method="post" action="{% url 'community:create_club' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class = "createclub-form">
                <div class = "form-group">
                    <label for="club_name">동아리명</label>
                    {{ form.club_name }}
                </div>
                <div class = "form-group">
                    <label for="club_num">동아리 인증 번호</label>
                    {{ form.club_num }}
                </div>
            </div>
            {% if form.club_name.errors %}
            <div class="message-container">
                {% for error in form.club_name.errors %}
                    {{ error }}
                {% endfor %}
            </div>
            {% endif %}
            <div class="button-container">
                <button type="submit" class="button">동아리 생성</button>
            </div>
        </form>
    </div>

{% endblock content %}

templates/community/create_post.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/community/create_post.css' %}" />

<h1 class="c_p_h1"> {{ board.board_name }} </h1>

<form method="post" class="c_p_form" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="c_p_Html">
        <label for="{{ form.title.id_for_label }}" class="c_p_form-label">제목</label>
        {{ form.title }}
    </div>

    <div class="c_p_Html">
        <label for="{{ form.content.id_for_label }}" class="c_p_form-label">내용</label>
        {{ form.content }}
    </div>

    <div class="c_p_Html">
        <label for="{{ form.image.id_for_label }}" class="c_p_form-label">이미지 업로드</label>
        {{ form.image }}
    </div>

    <div class="c_p_Html c_p_form-anony">
        {{ form.anonymous }}
        <label class="form-anony-label" for="{{ form.anonymous.id_for_label }}">익명</label>
    </div>

    <button type="submit" class="btn-create">게시글 업로드</button>
</form>

{% endblock content %}

templates/community/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block head %}

{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/reset.css' %}" />
<link rel="stylesheet" href="{% static 'css/community/post_list.css' %}" />
<div id="post_list">
    <div id="post_container">
        <div class="board-header">
            <h1 id="board__title">
                <a href="{% url 'community:post_list' board.id %}">
                    {{ board.board_name }}
                </a>
            </h1>
            {% if user.is_authenticated and board.board_name == "자유게시판" %}
            {% elif user.is_authenticated and board.board_name == "공지게시판" %}
            {% elif user.is_authenticated and board.board_name == "질문게시판" %}
            {% else %}
            <div id="delete-box">
                {% if messages %}
                <ul class="messages" style="display: flex; align-items: center;">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}
                        style="{% if 'error' in message.tags %}color: red;{% endif %}">
                        {{ message }}
                        </li>
                        {% endfor %}
                </ul>
                {% endif %}
                <div id="delete">
                    <form method="post" action="{% url 'community:delete_board' board.id %}" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger" onclick="return fn_del_qna();">게시판 삭제</button>
                    </form>
                </div>
            </div>
            {% endif %}
        </div>
        <div class="search-container">
            <div class="search__bar board-search__bar">
                <form class="search" method="POST" action="{% url 'community:search' %}">
                    {% csrf_token %}
                    <input type="hidden" name="board_id" value="{{ board.id }}">
                    <button class="search-btn" type="submit">
                        <img src="/static/image/search_btn_icon.png" alt="검색버튼" id="search_btn_icon">
                    </button>
                    <input class="search-bar" type="search" placeholder="{{ board.board_name }}의 글을 검색하세요"
                        name="searched">
                </form>
            </div>
        </div>
        <div id="board__container">
            <button id="show-post-form" class="btn btn-primary">게시글 작성</button>
            <div id="post-form-container" style="display: none;">
                <form id="post-form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <!-- form 수동 설정 -->
                    <div class="form-group">
                        <label for="id_title">게시글 제목</label>
                        {{ form.title }}
                    </div>

                    <div class="form-group">
                        <label for="id_content">게시글 내용</label>
                        {{ form.content }}
                    </div>

                    <div class="form-group-inline">
                        {{ form.anonymous }} <label for="id_anonymous">익명</label>
                    </div>

                    <div class="form-group-inline">
                        <label for="id_image">Image</label> {{ form.image }}
                    </div>

                    <div class="form-buttons" style="text-align: right;">
                        <button type="submit" class="btn btn-success">저장</button>
                        <button type="button" id="cancel-post" class="btn btn-secondary">취소</button>
                    </div>
                </form>
            </div>
            <ul id="post__ul_pinned">
                {% for post in posts %}
                {% if post.pinned %}
                <a href="{% url 'community:post_detail' board.id post.id %}">
                    <li class="post_pinned_container">
                        <h2 id="post__title">
                            <img src="../../static/image/pinned_icon.png" alt="고정"
                                style="vertical-align: middle; width: 20px; height: 20px;" />
                            {{ post.title }}
                        </h2>
                        <p id="post__content">{{ post.content|truncatewords:20 }}</p>
                        <div id="post__description">
                            <p id="post__created">{{ post.created_time|date:"Y/m/d" }}</p>
                            <!-- 공지게시판일 경우 무조건 실명으로 표시 -->
                            {% if board.board_name == "공지게시판" %}
                            <p id="post__user">{{ post.user_id.name }}</p>
                            {% elif post.anonymous is True %}
                            <p id="post__user">익명</p>
                            {% else %}
                            <p id="post__user">{{ post.user_id.nickname }}</p>
                            {% endif %}
                            <!-- <div id="post__stats">
                                    <p>댓글 수: {{ post.comment_set.count }}</p>
                                    <p>좋아요 수: {{ post.liked_by.count }}</p>
                                    <p>스크랩 수: {{ post.scraped_by.count }}</p>
                                </div> -->
                            <!-- 좋댓구 이미지변환, 0이면 출력 X -->
                            <div class="state__container">
                                {% if post.liked_by.count %}
                                <div class="state__content">
                                    <div class="like__container">
                                        <img src="/../../static/image/like__icon.png" alt="좋아요">
                                    </div>
                                    <span id="like__description" class="like__description">
                                        {{ post.liked_by.count }}</span>
                                </div>
                                {% endif %}
                                {% if post.comment_set.count %}
                                <div class="state__content">
                                    <div class="comment__container">
                                        <img src="/../../static/image/comment__icon.png" alt="댓글">
                                    </div>
                                    <span class="comment__description">{{ post.comment_set.count }}</span>
                                </div>
                                {% endif %}
                                {% if post.scraped_by.count %}
                                <div class="state__content">
                                    <div class="scrap__container">
                                        <img src="/../../static/image/scrap__icon.png" alt="스크랩">
                                    </div>
                                    <span id="scrap__description" class="scrap__description">
                                        {{ post.scraped_by.count }}</span>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </li>
                </a>
                {% endif %}
                {% endfor %}
            </ul>

            <ul id="post__ul">
                {% for post in posts %}
                {% if not post.pinned %}
                <a href="{% url 'community:post_detail' board.id post.id %}">
                    <li>
                        <h2 id="post__title">{{ post.title|truncatewords:10 }}</h2>
                        <p id="post__content">{{ post.content|truncatewords:20 }}</p>
                        <div id="post__description">
                            <p id="post__created">{{ post.created_time|date:"Y/m/d" }}</p>
                            <!-- 공지게시판일 경우 무조건 실명으로 표시 -->
                            {% if board.board_name == "공지게시판" %}
                            <p id="post__user">{{ post.user_id.name }}</p>
                            {% elif post.anonymous is True %}
                            <p id="post__user">익명</p>
                            {% else %}
                            <p id="post__user">{{ post.user_id.nickname }}</p>
                            {% endif %}
                            <!-- <div id="post__stats">
                                    <p>댓글 수: {{ post.comment_set.count }}</p>
                                    <p>좋아요 수: {{ post.liked_by.count }}</p>
                                    <p>스크랩 수: {{ post.scraped_by.count }}</p>
                                </div> -->
                            <!-- 좋댓구 이미지변환, 0이면 출력 X -->
                            <div class="state__container">
                                {% if post.liked_by.count %}
                                <div class="state__content">
                                    <div class="like__container">
                                        <img src="/../../static/image/like__icon.png" alt="좋아요">
                                    </div>
                                    <span id="like__description" class="like__description">
                                        {{ post.liked_by.count }}</span>
                                </div>
                                {% endif %}
                                {% if post.comment_set.count %}
                                <div class="state__content">
                                    <div class="comment__container">
                                        <img src="/../../static/image/comment__icon.png" alt="댓글">
                                    </div>
                                    <span class="comment__description">{{ post.comment_set.count }}</span>
                                </div>
                                {% endif %}
                                {% if post.scraped_by.count %}
                                <div class="state__content">
                                    <div class="scrap__container">
                                        <img src="/../../static/image/scrap__icon.png" alt="스크랩">
                                    </div>
                                    <span id="scrap__description" class="scrap__description">
                                        {{ post.scraped_by.count }}</span>
                                </div>
                                {% endif %}
                            </div>
                    </li>
                </a>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="side__container">
        <div class="profile__container">
            <div class="board__title">내 정보</div>
            <ul class="best__ul">
                <div class="profile_content"><span class="profile-bold-text">닉네임</span> {{ user.nickname }}</div>
                <div class="profile_content"><span class="profile-bold-text">접속 동아리</span>
                    {{ request.session.club_name }}</div>
                <div class="mypage__container">
                    <a href="{% url 'mypage:main' %}">
                        <button id="mypage__btn">마이페이지</button>
                    </a>
            </ul>
        </div>
        <div class="best__container">
            <div class="board__title">베스트 게시글</div>
            <ul class="best__ul">
                {% for post in posts_best %}
                <li class="best__li">
                    <div class="best__name">
                        <a href="{% url 'community:post_detail' post.board_id.id post.id %}">
                            <div>{{ post.title|truncatechars:7 }}</div>
                            <div class="time__container">{{ post.created_time|date:"Y/m/d" }}</div>
                        </a>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

<script src="{% static 'js/community/post_list.js' %}"></script>
<script>
    function fn_del_qna() {
        var res = confirm('게시판을 정말로 삭제하시겠습니까?');
        if (res) {
            // "확인"을 누른 경우에만 삭제 요청을 진행
        } else {
            // "취소"를 누른 경우, 아무 동작도 하지 않음
            return false;  // 폼 제출을 중단
        }
    }
</script>

{% endblock %}