apps/community/urls.py
from django.urls import path
from django.shortcuts import render
from .views import *

# from * import views

app_name = "community"

urlpatterns = [
    path("<int:board_id>/", post_list, name="post_list"),
    path("<int:board_id>/post/<int:post_id>/", post_detail, name="post_detail"),
    path("<int:board_id>/create/", create_post, name="create_post"),
    path("create_board/", create_board, name="create_board"),
    path("", main, name="main"),
    path("<int:board_id>/delete/", delete_board, name="delete_board"),
    path("create_club/", create_club, name="create_club"),
    path("select_club/", select_club, name="select_club"),
    path("post/<int:post_id>/scrap/", scrap_post, name="scrap_post"),
    path("post/<int:post_id>/like/", like_post, name="like_post"),
    path(
        "<int:board_id>/post/<int:post_id>/create_comment/",
        create_comment,
        name="create_comment",
    ),
    path(
        "<int:board_id>/post/<int:post_id>/toggle_pinned/",
        toggle_pinned,
        name="toggle_pinned",
    ),
    path("post/<int:post_id>/delete/", delete_post, name="delete_post"),
    path("comment/<int:comment_id>/delete/", delete_comment, name="delete_comment"),
    path("search", search, name="search"),
    path("load-more-boards/", load_more_boards, name="load_more_boards"),
    path("<int:post_id>/delete_post/", delete_post, name="delete_post"),
]

apps/landing/urls.py
from django.urls import path,include 
from .views import *
#from django.contrib.auth import views as auth_views
from . import views

app_name = "landing"

urlpatterns = [
    path("", main, name="main"),
    path("signup/", signup, name="signup"),
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
    path("delete/<int:id>/", delete, name="delete"),
    path("update/",update, name="update"),
    path('change_password/',change_password, name="change_password"),
    path("club_auth/", club_auth, name="club_auth"),

    path('find_username/', find_username, name='find_username'),
    path('find_username_result/',find_username_result, name='find_username_result'),
]

apps/mypage/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from . import views

app_name = "mypage"

urlpatterns = [
    path("", main, name="main"),
    path("myposts/", myposts, name="myposts"),
    path("mycomments/", mycomments, name="mycomments"),
    path("myscraps/", myscraps, name="myscraps"),
    path('manage-clubs/', views.manage_clubs, name='manage_clubs'),
    path('delete-club/', views.delete_club, name='delete_club'),
    path('switch_club/<int:club_id>/', views.switch_club, name='switch_club'),
    path('webpush/get_status/', views.get_status, name='get_status'),
]

apps/schedule/urls.py
from django.urls import path
from .views import *

app_name = "schedule"

urlpatterns = [
    path("event_list/", event_list, name="event_list"),
    path("event_create/", event_create, name="event_create"),
    path("event_update/", event_update, name="event_update"),
    path("event_delete/", event_delete, name="event_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.landing.urls")),  # 랜딩 페이지 ~ 동아리 인증페이지까지
    path("community/", include("apps.community.urls")),  # 메인 페이지 ~ 모든 기능
    path("chat/", include("apps.chat.urls")),  # 채팅방 리스트, 채팅방
    path("mypage/", include("apps.mypage.urls")),  # 마이페이지 내 모든 기능
    path("schedule/", include("apps.schedule.urls")),
    path("", include("django.contrib.auth.urls")),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="registration/password_reset_form.html"
        ),
        name="password_reset_form",
    ),
    path(
        "password_reset_done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="registration/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("webpush/", include("webpush.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{% static 'css/reset.css' %}" />
  <link rel="icon" href="/static/image/logo_background.PNG">
  <script src="https://kit.fontawesome.com/ff7a5a86fb.js" crossorigin="anonymous"></script>
  <title>동아리타임!</title>
  {% block extra_head %}{% endblock extra_head %}
  {% block head %}{% endblock head %}
</head>

<body>
  {% include 'header.html'%}
  {% block content %}{% endblock%}
  {% include 'footer.html'%}

</body>

</html>

templates/footer.html
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}" />
    <link rel="stylesheet" href="{% static 'css/footer.css' %}" />
</head>
<footer class="footer_content">
ⓒ 2024, DongAri_Time All rights reserved.
</footer>

templates/header.html
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/header.css' %}" />
</head>
<header>

{% if user.is_authenticated %}
    {% if request.session.club_id %}
    <div class="main_header__container">
        <a href="{% url 'community:main' %}">
            <div class="main_left__container__session">
                    <div class="main_app__icon">
                        <img src="/static/image/logo.png" alt="로고" id="club_logo">
                    </div>
                    <div class="main_title">
                        <div class="main_app__small_title">동아리타임</div>
                        <div class="main_app__title">{{ request.session.club_name|truncatechars:7 }}</div>
                    </div>
            </div>
        </a>
        <div class="main_right__container__session">
            <div class="search__bar">
                <form class="search" method="POST" action="{% url 'community:search' %}">
                    {% csrf_token %}       
                    <button class="search-btn" type="submit"> 
                        <img src="/static/image/search_btn_icon.png" alt="검색버튼" id="search_btn_icon">
                    </button> 
                    <input class="search-bar" type="search" placeholder="게시판의 글을 검색하세요" name="searched">
                </form>
            </div>
            <button id="main_mypage_btn"><a href="{% url 'mypage:main' %}">
                <img src="/static/image/mypage__icon.png" alt="마이페이지" id="mypage_icon">
            </a></button>
            <button id="main_calender_btn"><a href="{% url 'schedule:event_list'%}">
                <img src="/static/image/calender.png" alt="캘린더" id="calender_icon">
            </a></button>
            <button id="main_logout_btn"><a href="{% url 'landing:logout' %}">
                <img src="/static/image/logout__icon.png" alt="로그아웃" id="logout_icon">
            </a></button>
        </div>
    </div>
    {% else %}    
    <div class="header__container">        
        <div class="left__container__login">
            <button id="prev_btn" onclick="prev()">
                <img src="/static/image/arrow_back.png" alt="뒤로 가기" id="arrow_back">
            </button>
        </div>
        <div class="center__container__login">
            <div class="app__icon">
                <img src="/static/image/logo.png" alt="로고" id="club_logo">
            </div>
            <div class="app__title">동아리타임</div>
        </div>
        <div class="right__container__login">
            <button id="logout_btn"><a href="{% url 'landing:logout' %}">로그아웃</a></button>
        </div>
    </div>
{% endif %}            
{% else %}
<div class="header__container">        
    <div class="left__container__login">
        <button id="prev_btn" onclick="prev()">
            <img src="/static/image/arrow_back.png" alt="뒤로 가기" id="arrow_back">
        </button>
    </div>
    <div class="center__container__login">
        <div class="app__icon">
            <img src="/static/image/logo.png" alt="로고" id="club_logo">
        </div>
        <div class="app__title">동아리타임</div>
    </div>
    <div class="right__container__login">
    </div>
</div>
{% endif %}
{% if user.is_authenticated %}
{% if request.session.club_id %}
<div class="board__header">
    <div class="board__container">
        {% for board in boards %}
        <div id="main_board__name"><a href="{% url 'community:post_list' board.id %}">{{ board.board_name|truncatechars:7 }}</a></div>
        {% endfor %}
    </div>
    <div id="button__container">
        <a href="{% url 'community:create_board' %}">
            <button id="main_btn">
                        <div id="select__box">
                            <div id="icon__box">
                                <img src="/static/image/plus.png" alt="게시판 추가" id="plus">
                            </div>
                        </div>
            </button>
            <div id="add-btn">게시판 추가</div>
        </a>
    </div>
</div>
    {% endif %}
{% endif %}
</header>
<script>
    const prev = () => {
        window.history.back();
    }
</script>