apps/landing/urls.py
from django.urls import path,include 
from .views import *
#from django.contrib.auth import views as auth_views
from . import views

app_name = "landing"

urlpatterns = [
    path("", main, name="main"),
    path("signup/", signup, name="signup"),
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
    path("delete/<int:id>/", delete, name="delete"),
    path("update/",update, name="update"),
    path('change_password/',change_password, name="change_password"),
    path("club_auth/", club_auth, name="club_auth"),

    path('find_username/', find_username, name='find_username'),
    path('find_username_result/',find_username_result, name='find_username_result'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.landing.urls")),  # 랜딩 페이지 ~ 동아리 인증페이지까지
    path("community/", include("apps.community.urls")),  # 메인 페이지 ~ 모든 기능
    path("chat/", include("apps.chat.urls")),  # 채팅방 리스트, 채팅방
    path("mypage/", include("apps.mypage.urls")),  # 마이페이지 내 모든 기능
    path("schedule/", include("apps.schedule.urls")),
    path("", include("django.contrib.auth.urls")),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="registration/password_reset_form.html"
        ),
        name="password_reset_form",
    ),
    path(
        "password_reset_done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="registration/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("webpush/", include("webpush.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/landing/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from .models import User
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

class SignupForm(UserCreationForm):
    username = forms.CharField(
        label="아이디", widget=forms.TextInput(attrs={"class": "signup-input"}),
        required=True
    )
    password1 = forms.CharField(
        label="비밀번호", widget=forms.PasswordInput(attrs={"class": "signup-input"}),
        required=True
    )
    password2 = forms.CharField(
        label="비밀번호 확인",widget=forms.PasswordInput(attrs={"class": "signup-input"}),
        required=True
    )
    name = forms.CharField(
        label="이름", widget=forms.TextInput(attrs={"class": "signup-input"}),
        required=True
    )
    nickname = forms.CharField(
        label="닉네임", widget=forms.TextInput(attrs={"class": "signup-input"}),
        required=True
    )
    phone_num = forms.CharField(
        label="전화번호", widget=forms.TextInput(attrs={"class": "signup-input"}),
        required=True
    )
    email = forms.EmailField(
            label="이메일", widget=forms.EmailInput(attrs={"class": "signup-input"}),
            required=True
        )
    
    class Meta:
        model = User
        fields = [
            "username",
            "password1",
            "password2",
            "name",
            "nickname",
            "phone_num",
            "email",
        ]

class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = [
            "nickname",
            "phone_num",
            "email",
        ]
    def clean_nickname(self):
        nickname = self.cleaned_data.get('nickname')
        if User.objects.filter(nickname=nickname).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError('이미 사용 중인 닉네임입니다.')
        return nickname

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError('이미 사용 중인 이메일입니다.')
        return email

    def clean_phone_num(self):
        phone_num = self.cleaned_data.get('phone_num')
        if User.objects.filter(phone_num=phone_num).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError('이미 사용 중인 전화번호입니다.')
        return phone_num
    
#아이디찾기
from django import forms

class FindUsernameForm(forms.Form):
    name = forms.CharField(label='이름', max_length=20, required=True)
    email = forms.EmailField(label='이메일', max_length=20, required=True)

templates/users/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/reset.css' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/reset.css' %}">
<link rel="stylesheet" href="{% static 'css/mypage/mypage.css' %}">
<link rel="stylesheet" href="{% static 'css/users/change_password.css' %}">

<div class="manage_clubs__body">
  <div class="title__container">
    <h1 class="page__title">비밀번호 변경 🔐</h1>
    <hr class="page__title_hr">
  </div>
  <form method="post" action="{% url 'landing:change_password' %}">
    {% csrf_token %}
    <div class="changepassword-form">
      <div class="changepassword-form-container">
        <div class="form-group">
          <label for="id_old_password">기존 비밀번호</label>
          {{ form.old_password }}
        </div>
        <div class="form-group">
            <label for="id_new_password1">새 비밀번호</label>
            {{ form.new_password1 }}
        </div>            
        <div class="form-group">
            <label for="id_new_password2">새 비밀번호 확인</label>
            {{ form.new_password2 }}
        </div>
        <div class="message-container">
          {% if messages %}
          <ul>
              {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
              {% endfor %}
          </ul>
          {% endif %}
        </div>
        <div class="button-container">
          <button type="submit" class="button">비밀번호 변경</button>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}

templates/users/find_username.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/reset.css' %}">
<link rel="stylesheet" href="{% static 'css/users/find_username.css' %}">
<link rel="stylesheet" href="{% static 'css/users/signup.css' %}">

    <div id="findusername-container">
        <h3>아이디 찾기</h3>
        <form method="post" action="{% url 'landing:find_username' %}">
            {% csrf_token %}
            <div class="findusername-form">
                <div class="form-group">
                    <label for="name">사용자 이름</label>
                    <input type="text" name="name" id="name" placeholder="실명" value="{{ form.name.value|default_if_none:'' }}">
                </div>
                <div class="form-group">
                    <label for="email">이메일</label>
                    <input type="email" name="email" id="email" placeholder="이메일" value="{{ form.email.value|default_if_none:'' }}">
                </div>
            </div>
            <div class="button-container">
                <button type="submit" class="button">아이디 찾기</button>
            </div> 
            <div class ="message-container">
                {% if form.errors %}
                    <ul>
                        {% for field, errors in form.errors.items %}
                            <li>{{ errors|striptags }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </form>
    </div>
    </div>
</body>
</html>

{% endblock %}

templates/users/find_username_result.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/reset.css' %}">
<link rel="stylesheet" href="{% static 'css/users/find_username_result.css' %}">
<link rel="stylesheet" href="{% static 'css/users/signup.css' %}">

    <div id = "usernameresult-container">
        <h3>아이디 찾기</h3>
            <div class="usernameresult-form">
                {% if username %}
                    <p>찾으신 아이디는 <strong>{{ username }}</strong> 입니다.</p>
                {% else %}
                    <p>아이디를 찾을 수 없습니다.</p>
                {% endif %}
            </div>
            <div class ="button-container">
                <p><a href='{% url "landing:login" %}'>로그인 페이지</a></p>
            </div>
    </div>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/users/login.css' %}">
    <link rel="stylesheet" href="{% static 'css/users/signup.css' %}">

    <div id="login-container">
            <h3>로그인</h3>
        <form method="post" action="{% url 'landing:login' %}">
            {% csrf_token %}
            <div class = "login-form">
                <div class = "form-group">
                    <label for="username">아이디</label>
                    <input id="username" name="username" type="text" placeholder="아이디">
                </div>
                <div class="form-group">
                    <label for="password">비밀번호</label>
                    <input id="password" name="password" type="password" placeholder="비밀번호">
                </div>
            </div>
            <div class="find-container">
                <div class ="find-form">
                    <p><a href='{% url "landing:find_username" %}'>아이디 찾기</a></p>
                </div>
                <div class ="find-form">
                    <p><a href='{% url "password_reset" %}'>비밀번호 찾기</a></p>
                </div>
                <div class ="find-form">
                    <p><a href='{% url "landing:signup" %}'>회원가입</a></p>
                </div>
            </div>
            <div class="message-container">
                {% if messages %}
                <ul>
                    {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
            <div class="button-container">
                <button type="submit" class="button">로그인</button>
            </div>
        </form>
    </div>
</body>
</html>
{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/reset.css' %}">
<link rel="stylesheet" href="{% static 'css/users/signup.css' %}">

<div id="signup-container">
        <h3>회원가입</h3>
        <form method="post" action="{% url 'landing:signup' %}">
            {% csrf_token %}
            <div class="signup-form">
                <!-- 아이디 입력 -->
                <div class="form-group">
                    <label for="username">아이디</label>
                    <input type="text" name="username" id="username" minlength="4" maxlength="15" placeholder="4~15글자 입력" value="{{ form.username.value|default_if_none:'' }}">
                </div>
                
                <!-- 비밀번호 입력 -->
                <div class="form-group">
                    <label for="password1">비밀번호</label>
                    <input type="password" name="password1" id="password1" minlength="8" placeholder="8글자 이상 입력" value="{{ form.password1.value|default_if_none:'' }}">
                </div>
                
                <!-- 비밀번호 확인 -->
                <div class="form-group">
                    <label for="password2">비밀번호 확인</label>
                    <input type="password" name="password2" id="password2" minlength="8" placeholder="8글자 이상 입력" value="{{ form.password2.value|default_if_none:'' }}">
                </div>
                
                <!-- 사용자 이름 -->
                <div class="form-group">
                    <label for="name">사용자 이름</label>
                    <input type="text" name="name" id="name" placeholder="실명으로 입력" value="{{ form.name.value|default_if_none:'' }}">
                </div>
                
                <!-- 닉네임 -->
                <div class="form-group">
                    <label for="nickname">닉네임</label>
                    <input type="text" name="nickname" id="nickname" value="{{ form.nickname.value|default_if_none:'' }}">
                </div>
                
                <!-- 전화번호 -->
                <div class="form-group">
                    <label for="phone_num">전화번호</label>
                    <input type="tel" name="phone_num" id="phone_num" pattern="[0-9]{3}-[0-9]{4}-[0-9]{4}" placeholder="010-0000-0000" value="{{ form.phone_num.value|default_if_none:'' }}">
                </div>
                
                <!-- 이메일 -->
                <div class="form-group">
                    <label for="email">이메일</label>
                    <input type="email" name="email" id="email" placeholder="email" value="{{ form.email.value|default_if_none:'' }}">
                </div>
            </div>

            <!-- 폼 오류 메시지 -->
            {% if form.errors %}
            <div class="message-container">
                <p>다음 항목에 오류가 있습니다. 입력 정보를 확인해 주세요.</p>
                <ul>
                    {% for field, errors in form.errors.items %}
                        <li>{{ errors|striptags }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            <!-- 회원가입 버튼 -->
        <div class="button-container">
                <button type="submit" class="button">회원가입</button>
        </div>
    </form>
</div>

<script>
        document.getElementById('phone_num').addEventListener('input', function(e) {
            var value = e.target.value.replace(/[^0-9]/g, '');
            var formattedValue = '';
            if (value.length > 3 && value.length <= 7) {
                formattedValue = value.substr(0, 3) + '-' + value.substr(3);
            } else if (value.length > 7) {
                formattedValue = value.substr(0, 3) + '-' + value.substr(3, 4) + '-' + value.substr(7);
            } else {
                formattedValue = value;
            }
            e.target.value = formattedValue;
        });
    </script>
{% endblock content %}

templates/users/update.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/reset.css' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/reset.css' %}">
<link rel="stylesheet" href="{% static 'css/mypage/mypage.css' %}">
<link rel="stylesheet" href="{% static 'css/users/update.css' %}">

<div class="manage_clubs__body">
    <div class="title__container">
        <h1 class="page__title">회원정보 수정 🫧</h1>
        <hr class="page__title_hr">
    </div>
    <form method="post" action="{% url 'landing:update' %}">
        {% csrf_token %}
        <div class = "update-form">
            <div class="update-form-container">
                <div class="form-group">
                    <label for="id_nickname">닉네임</label>
                    {{ form.nickname }}  
                </div>
                <div class="form-group">
                    <label for="id_phone_num">전화번호</label>
                    {{ form.phone_num }}  
                </div>
                <div class="form-group">
                    <label for="id_email">이메일</label>
                    {{ form.email }}  
                </div>
                <div class="button-container">
                    <button type="submit" class="button">수정하기</button>
                </div>
            </div>
        </div>
    </form>
    <div class="button-container_parent">
        <div class="button-container">
            {% if user.is_authenticated and user.id %}
            <form action="{% url 'landing:delete' user.id %}" method ='POST'>
                {% csrf_token %}
                <input id="button" type="submit" value='회원탈퇴'>
            </form>
        </div>
    </div>
</div>


<script>
    document.getElementById('id_phone_num').addEventListener('input', function(e) {
        var value = e.target.value.replace(/[^0-9]/g, '');
        var formattedValue = '';
        if (value.length > 3 && value.length <= 7) {
            formattedValue = value.substr(0, 3) + '-' + value.substr(3);
        } else if (value.length > 7) {
            formattedValue = value.substr(0, 3) + '-' + value.substr(3, 4) + '-' + value.substr(7);
        } else {
            formattedValue = value;
        }
        e.target.value = formattedValue;
    });
</script>
{% else %}
<p>로그인이 필요합니다.</p>
{% endif %}
</div>
{% endblock content %}